name: 01-building-blocks
on:
  - push
  - workflow_dispatch
jobs:
  echo-hello:
    run-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Hello World"
  echo-goodbye:
    run-on: ubuntu-latest
    steps:
      - name: Failed step
        run: echo "I" echo "will" echo "fail"
      - name: Say Goodbye
        run: echo "Goodbye!"
