name: Build Workflow

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate build number
        run: echo "${{ github.run_number }}" > build_number.txt

      - name: Upload build number
        uses: actions/upload-artifact@v4
        with:
          name: build-number
          path: build_number.txt
